//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MergeViral.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailNotification
    {
        public int Id { get; set; }
        public int CampaignId { get; set; }
        public Nullable<bool> SendAfterRegistration { get; set; }
        public Nullable<bool> SendWhenSignsUp { get; set; }
        public Nullable<bool> SendWhenRewardUnlocked { get; set; }
        public string FromName { get; set; }
        public string FromEmail { get; set; }
        public string ServerHost { get; set; }
        public Nullable<int> ServerPort { get; set; }
        public string Password { get; set; }
        public string EncryptionType { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual Campaign Campaign { get; set; }
    }
}
