//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MergeViral.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward
    {
        public int Id { get; set; }
        public int CampaignId { get; set; }
        public int RewardTypeId { get; set; }
        public string Name { get; set; }
        public int PointsMinimum { get; set; }
        public Nullable<int> PointsDirectSignUp { get; set; }
        public Nullable<int> PointsReferredSignUp { get; set; }
        public Nullable<int> PointsReferredLead { get; set; }
        public Nullable<int> PointsFacebook { get; set; }
        public Nullable<int> PointsTwitter { get; set; }
        public Nullable<int> PointsGoogle { get; set; }
        public Nullable<int> PointsLinkedIn { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual RewardType RewardType { get; set; }
    }
}
