//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MergeViral.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialPost
    {
        public int Id { get; set; }
        public int CampaignId { get; set; }
        public int SocialPostTypeId { get; set; }
        public string HandleName { get; set; }
        public string StandardTweet { get; set; }
        public string EmailSubject { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Img { get; set; }
        public string ReferralLink { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual SocialPostType SocialPostType { get; set; }
    }
}
